classdef Bot_status < ros.Message
    %Bot_status MATLAB implementation of bot_control/Bot_status
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2021 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'bot_control/Bot_status' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '3db43162dd15c0db30bd19667fefccf1' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Status
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Status'} % List of non-constant message properties
        ROSPropertyList = {'status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Bot_status(msg)
            %Bot_status Construct the message object Bot_status
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            javaArray = obj.JavaMessage.getStatus;
            array = obj.readJavaArray(javaArray, 'int16');
            status = int16(array);
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            if ~isvector(status) && isempty(status)
                % Allow empty [] input
                status = int16.empty(0,1);
            end
            
            validateattributes(status, {'numeric'}, {'vector'}, 'Bot_status', 'Status');
            
            javaArray = obj.JavaMessage.getStatus;
            array = obj.writeJavaArray(status, javaArray, 'int16');
            obj.JavaMessage.setStatus(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Status = obj.Status;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Status = strObj.Status;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Status = obj.Status;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.bot_control.Bot_status.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.bot_control.Bot_status;
            obj.reload(strObj);
        end
    end
end
