classdef Poses < ros.Message
    %Poses MATLAB implementation of bot_control/Poses
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2021 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'bot_control/Poses' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '709f184fa22f25c17cdd3e083652197b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPointClass = ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point') % Dispatch to MATLAB class for message type geometry_msgs/Point
    end
    
    properties (Dependent)
        Posei
    end
    
    properties (Access = protected)
        Cache = struct('Posei', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Posei'} % List of non-constant message properties
        ROSPropertyList = {'posei'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Poses(msg)
            %Poses Construct the message object Poses
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function posei = get.Posei(obj)
            %get.Posei Get the value for property Posei
            if isempty(obj.Cache.Posei)
                javaArray = obj.JavaMessage.getPosei;
                array = obj.readJavaArray(javaArray, obj.GeometryMsgsPointClass);
                obj.Cache.Posei = feval(obj.GeometryMsgsPointClass, array);
            end
            posei = obj.Cache.Posei;
        end
        
        function set.Posei(obj, posei)
            %set.Posei Set the value for property Posei
            if ~isvector(posei) && isempty(posei)
                % Allow empty [] input
                posei = feval([obj.GeometryMsgsPointClass '.empty'], 0, 1);
            end
            
            validateattributes(posei, {obj.GeometryMsgsPointClass}, {'vector'}, 'Poses', 'Posei');
            
            javaArray = obj.JavaMessage.getPosei;
            array = obj.writeJavaArray(posei, javaArray, obj.GeometryMsgsPointClass);
            obj.JavaMessage.setPosei(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Posei)
                obj.Cache.Posei = [];
                obj.Cache.Posei = obj.Posei;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Posei = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Posei = copy(obj.Posei);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            PoseiCell = arrayfun(@(x) feval([obj.GeometryMsgsPointClass '.loadobj'], x), strObj.Posei, 'UniformOutput', false);
            obj.Posei = vertcat(PoseiCell{:});
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Posei = arrayfun(@(x) saveobj(x), obj.Posei);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.bot_control.Poses.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.bot_control.Poses;
            obj.reload(strObj);
        end
    end
end
